services:
  postgres:
    container_name: postgres_api
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql