services:
  evolution-api:
      container_name: evolution_api
      image: evoapicloud/evolution-api:latest
      ports:
        - "8080:8080"
      env_file:
        - .env
      volumes:
        - evolution_instances:/evolution/instances
      depends_on:
        - postgres
        - redis
  postgres:
    image: postgres:15
    command: ["postgres", "-c", "max_connections=1000"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:latest
    container_name: redis_evolution_api
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - redis:/data
    ports:
      - 6379:6379